spring:
  main:
    allow-bean-definition-overriding: 'true'
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/${DBNAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

jwt:
  header: ${HEADER}
  prefix: ${PREFIX}
  secret: ${SECRET}
  exp:
    access: ${ACCESS}
    refresh: ${REFRESH}