spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    open-in-view: false

  jwt:
    secret: ${JWT_SECRET_KEY}
    exp:
      access: ${JWT_EXP_ACCESS}
      refresh: ${JWT_EXP_REFRESH}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
